version: "2"

services:

  app:
    build: .
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db
    environment:
      DJANGO_SU_EMAIL: ${DJANGO_SU_EMAIL}
      DJANGO_SU_PASSWORD: ${DJANGO_SU_PASSWORD}

  db:
    image: "postgres:10"
    env_file:
      - .env

    ports:
      - "5432:5432"
    networks:
      - backend

  db-admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge