# Generated by Django 3.0.8 on 2020-07-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default=models.CharField(max_length=255, unique=True), max_length=124, unique=True),
        ),
    ]
