# Generated by Django 3.0.8 on 2020-09-08 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_comment_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.Publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='media',
            field=models.FileField(upload_to='static/uploads/'),
        ),
    ]
