# Generated by Django 3.0.8 on 2020-09-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='follows', to='accounts.Profile'),
        ),
    ]
