# Generated by Django 3.0.8 on 2020-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200901_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='_profile_followers_+', to='accounts.Profile'),
        ),
    ]
