# Generated by Django 3.0.8 on 2020-09-19 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200918_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('following_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='accounts.Profile')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='accounts.Profile')),
            ],
        ),
    ]
